import vapoursynth as vs #non serve ma mi secca vedere robe rosse

class adenoise:
    @staticmethod
    def __init__(): ...
    @staticmethod
    def scan65mm(clip:vs.VideoNode, **kwargs): ...
    @staticmethod
    def scan35mm(clip:vs.VideoNode, **kwargs): ...
    @staticmethod
    def scan16mm(clip:vs.VideoNode, **kwargs): ...
    @staticmethod
    def scan8mm(clip:vs.VideoNode, **kwargs): ...
    @staticmethod
    def digital(clip:vs.VideoNode, **kwargs): ...